// src/Page/monthlyPlans.js

export const monthlyPlans = [
  {
    id: 1,
    planName: "5G135",
    dataValue: 4,
    dataUnit: "GB",
    price: "135.000đ",
    hasCallIcon: false,
    hasTv360Icon: true,
    hasCloudIcon: true,
  },
  {
    id: 2,
    planName: "5G150",
    dataValue: 6,
    dataUnit: "GB",
    price: "150.000đ",
    hasCallIcon: false,
    hasTv360Icon: true,
    hasCloudIcon: true,
  },
  {
    id: 3,
    planName: "5G160B",
    dataValue: 4,
    dataUnit: "GB",
    price: "160.000đ",
    hasCallIcon: true,
    hasTv360Icon: true,
    hasCloudIcon: true,
  },
  {
    id: 4,
    planName: "5G180B",
    dataValue: 6,
    dataUnit: "GB",
    price: "180.000đ",
    hasCallIcon: true,
    hasTv360Icon: true,
    hasCloudIcon: true,
  },
  {
    id: 5,
    planName: "5G230B",
    dataValue: 8,
    dataUnit: "GB",
    price: "2300.000đ",
    hasCallIcon: true,
    hasTv360Icon: true,
    hasCloudIcon: true,
  },
];